### PR TITLE
Add functionality to compute the Ellipticity-Direction correlation function 

### PR DESCRIPTION
**Pull request by EiffL**
The E-D correlation, used for intrinsic alignment studies, weights each (galaxy, tracer) pair by the cross product between the 3D major axis  of the galaxy and the normalised separation vector between the galaxy and tracer. See for instance Eq. 8 in arXiv:1409.7297 
In order to do this, I have added another type of "field" for 3D vectors and implemented an NV correlation that essentially computes this E-D correlation. This type of computation is only defined and implemented for 3d cartesian coordinates.

### CODE REVIEW

**Comment by EiffL** [comment]
So, after thinking about it, the only way I see to compute this ED correlation correctly is to force the split of the cells that contain the vector of galaxies major axes.
That would happen somewhere here https://github.com/rmjarvis/TreeCorr/blob/26d4169fe4cd7e599f2525b0aa9ad1d15e973676/src/BinnedCorr2.cpp#L298
Function BinnedCorr2() could be specialised when used on my new VData type to force splitting all the cells of that type, and then things should be fine.... But it's a little bit of a hack...

**Comment by rmjarvis** [comment]
Better would be to do it at the python layer and just set bin_slop = 0 automatically for ED correlations.

**Comment by EiffL** [comment]
oups, ok, sorry saw your  reply after making the changes, I'll look at whether I can  do the  same thing with bin_slop, I agree it would way better

**Comment by EiffL** [comment]
So, actually it's not that simple, if I set bin_slop = 0 it gets applied to the 2 catalogs in the correlation and then it takes for ever. As far as I can see, there is no way to force the correlation to go to the leaves for only one of the 2 catalogs from the python.

**Comment by rmjarvis** [comment]
Hi Francois

Just checking in about this PR.  I didn't write it here it seems, but I think my main comment when we discussed this in person in Chicago was that there are no unit tests.  We discussed trying to come up with some analytically calculable results we could compare against.  And also some tests with few enough points that the brute force comparison is feasible.  

So I just wanted to check if you were still planning to work on this, or if you've moved on and aren't interested in working on this anymore.

**Comment by EiffL** [comment]
Hi Mike,
Full disclosure, I've been using another tool to compute this correlation function, and as a result I haven't spent much time on this since Chicago. 

Yes, I think what was needed were a few unit tests, but also, I think we discussed that it would nice to have an option to completely disable the tree approximation, and compute the correlation down to individual galaxies. This is required for this correlation function, and would be a nice feature in general. From what I remember, I started working on that and was half-way through modifying the C and python API...

Let me know if you think that would be useful to finish this PR :-) otherwise I'm ok with closing it for now and maybe re-opening it if anyone expresses interest in this functionality down the line.

**Comment by rmjarvis** [comment]
I'm planning on fairly significantly reworking the C++-layer to enable arbitrary binning.  Specifically the part where it decides when to progress down the tree.  So probably better to wait until that is done before working too hard on something that is closely connected to that.  I'll probably even include this feature as part of that effort.

Just to make sure I have it straight -- you wanted the ability to force going to the leaves for one of the two catalogs (or both, but in particular, not necessarily both).  Is this right?

**Comment by EiffL** [comment]
At least, that's what my code wanted to do. But actually, I can't remember why splitting only one of the catalogs was enough in this case. In the latest version of my code (that I haven't pushed), I added a keyword to the Cell<> and BuildXFieldXX constructors to force the split, of potentially both catalogs.

**Comment by rmjarvis** [comment]
Closing this, since it seems to be abandoned.

**Pull request closed without merging**
