### PR TITLE
Compatibility with Python 3

### PR DESCRIPTION
**Pull request by gogrean**
By default, installing the TreeCorr package fails with Python 3:

```
$ sudo pip install TreeCorr

Collecting TreeCorr
  Downloading TreeCorr-3.1.1.tar.gz (90kB)
    100% |████████████████████████████████| 94kB 3.3MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/tmp/pip-build-l957_r8f/TreeCorr/setup.py", line 8
        print 'Unable to import setuptools.  Using distutils instead.'
                                                                     ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-l957_r8f/TreeCorr
```

I've made some minor changes to make the code work both in Python 2.7 and in Python 3. I haven't tested it with older versions of Python.

### CODE REVIEW

**Comment by rmjarvis** [comment]
Thanks Georgiana.  I don't think I'm willing to commit to making sure the code stays in compliance with python 3, since I don't ever use it, and I don't know how many users there are who would care about this (no one has yet requested compliance with python 3 for instance).  

But if it's mostly just a matter of using the print function and this funny decode thing, then I guess it's not so onerous to maintain compliance with both.  I might have to rely on you (or others) to let me know if some future release ever stops working with python 3 though, since I probably won't notice, and I don't think I have a system on which to test it.  (I'll check around though.  There might be one somewhere I can try.)

Have you run the unit tests to make sure the code in general works with python 3 and there aren't other hidden gotchas?  In the tests directory, you should be able to run them by typing `nosetests`.

**Comment by rmjarvis** [comment]
OK, I realized I can install python3.4 on my laptop, so I did that, and the test suite also had lots of print statements to change.  2to3 worked for them.  But now there are 2 failures I need to figure out.  Once I figure them out, I'll get this merged and uploaded to pip as 3.1.2.

**Comment by gogrean** [comment]
Other than the many print statements, I had to change:

```
urllib.urlretrieve(url, file_name)
```

to:

```
import urllib.request
urllib.request.urlretrieve(url, file_name)
```

The only other failure I had was caused by the code not finding corr2. corr2 was in:

/opt/local/Library/Frameworks/Python.framework/Versions/3.4/bin/corr2

so the problem was solved with a soft link:
```
$ sudo ln -s /opt/local/Library/Frameworks/Python.framework/Versions/3.4/bin/corr2 /opt/local/bin/corr2
```

I'm guessing the problem with corr2 only happens on a Mac.

Are you running into other issues?

**Comment by gogrean** [comment]
This only works in Python 3, btw...

```
import urllib.request
urllib.request.urlretrieve(url, file_name)
```

**Comment by rmjarvis** [comment]
> This only works in Python 3, btw...
```
import urllib.request
urllib.request.urlretrieve(url, file_name)
```

Right.  For that, I switched to a try/except block to get it to work on both 2 and 3, so that's working now.  It shouldn't be too hard to maintain this.  Mostly I'll just have to get used to using the print functions rather than print statements.  I suppose I can handle that...  :)

**Comment by rmjarvis** [comment]
This is in version 3.1.2 now, installable via pip.  Thank again!

**Comment by jesford** [comment]
treecorr is working for me in my Python 3 environment, but NOT in Python 2 (not sure if I should open a separate issue, as I suspect this may be related to this fairly recent addition of Python 3 support?). 

```
import sys

print sys.version
2.7.11 |Anaconda 2.3.0 (x86_64)| (default, Dec  6 2015, 18:57:58) 
[GCC 4.2.1 (Apple Inc. build 5577)]

import treecorr
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-1-88d203157b69> in <module>()
----> 1 import treecorr

/Users/jesford/anaconda/lib/python2.7/site-packages/treecorr/__init__.py in <module>()
     17 from . import util
     18 from .celestial import CelestialCoord, angle_units, arcsec, arcmin, degrees, hours, radians
---> 19 from .config import read_config, set_omp_threads
     20 from .catalog import Catalog, read_catalogs, calculateVarG, calculateVarK
     21 from .binnedcorr2 import BinnedCorr2

/Users/jesford/anaconda/lib/python2.7/site-packages/treecorr/config.py in <module>()
    346 import numpy
    347 import ctypes
--> 348 _treecorr = numpy.ctypeslib.load_library('_treecorr',os.path.dirname(__file__))
    349 _treecorr.SetOMPThreads.restype = ctypes.c_int
    350 _treecorr.SetOMPThreads.argtypes = [ ctypes.c_int ]

/Users/jesford/anaconda/lib/python2.7/site-packages/numpy/ctypeslib.pyc in load_library(libname, loader_path)
    121             if os.path.exists(libpath):
    122                 try:
--> 123                     return ctypes.cdll[libpath]
    124                 except OSError:
    125                     ## defective lib file

/Users/jesford/anaconda/lib/python2.7/ctypes/__init__.pyc in __getitem__(self, name)
    438 
    439     def __getitem__(self, name):
--> 440         return getattr(self, name)
    441 
    442     def LoadLibrary(self, name):

/Users/jesford/anaconda/lib/python2.7/ctypes/__init__.pyc in __getattr__(self, name)
    433         if name[0] == '_':
    434             raise AttributeError(name)
--> 435         dll = self._dlltype(name)
    436         setattr(self, name, dll)
    437         return dll

/Users/jesford/anaconda/lib/python2.7/ctypes/__init__.pyc in __init__(self, name, mode, handle, use_errno, use_last_error)
    363 
    364         if handle is None:
--> 365             self._handle = _dlopen(self._name, mode)
    366         else:
    367             self._handle = handle

OSError: dlopen(/Users/jesford/anaconda/lib/python2.7/site-packages/treecorr/_treecorr.so, 6): Library not loaded: @rpath/./libgomp.1.dylib
  Referenced from: /Users/jesford/anaconda/lib/python2.7/site-packages/treecorr/_treecorr.so
  Reason: image not found
```

I can go ahead and use the Python 3 installation for now, but I just wanted to point out this error in case it had passed under the radar so far, or in case someone can tell me where I messed up. 

Thanks for this package, I'm looking forward to using it!

**Comment by rmjarvis** [comment]
This looks like an installation issue, not something related to python 2 vs 3.  It's looking for a gomp library in a strange place.  It has a relative path to it (that's the `@rpath` bit), which isn't right.  It should have an absolute path to something like /usr/lib/libgomp.1.dylib or something along those lines.  This should have been set by the Anaconda compiler/linker.  It's not something the the TreeCorr code does anything with.

How did you install treecorr for the 2.7 python?

I don't use anaconda for my primary python package, but when I do the following in the TreeCorr directory (version 3.2.3):
```
/anaconda/bin/python2.7 setup.py install
```
it seems to install everything correctly.  In my case, the treecorr package ends up in an egg file, which doesn't seem to be the case for your installation.
```
/anaconda/lib/python2.7/site-packages/TreeCorr-3.2.3-py2.7-macosx-10.5-x86_64.egg/
```
So maybe that's a clue.  Also, it isn't trying to use any gomp library:
```
$ otool -L /anaconda/lib/python2.7/site-packages/TreeCorr-3.2.3-py2.7-macosx-10.5-x86_64.egg/treecorr/_treecorr.so 
/anaconda/lib/python2.7/site-packages/TreeCorr-3.2.3-py2.7-macosx-10.5-x86_64.egg/treecorr/_treecorr.so:
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 111.1.4)
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```
Now, my machine doesn't have the latest clang version that has OpenMP, but when I jerry rig it to use that rather than the default clang compiler, I still don't get the weird `@rpath` bit.  In that case, it looks like:
```
$ otool -L /anaconda/lib/python2.7/site-packages/TreeCorr-3.2.3-py2.7-macosx-10.5-x86_64.egg/treecorr/_treecorr.so 
/anaconda/lib/python2.7/site-packages/TreeCorr-3.2.3-py2.7-macosx-10.5-x86_64.egg/treecorr/_treecorr.so:
	/sw/opt/llvm-3.7/lib/libomp.dylib (compatibility version 5.0.0, current version 5.0.0)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 111.1.4)
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```
It has an absolute path to /sw/opt/llvm-3.7/lib/libomp.dylib, not libgomp at all.  Which tells me that maybe your Anaconda is using some version of GNU gcc, rather than the Apple gcc (which is really clang).  If you look at the output during the setup.py installation, you should see some lines starting with
```
compiler version information: 
[...]
building 'treecorr._treecorr' extension
```
Let me know what the [...] is on your system.  That might help diagnose this.

My only suggestion at this point is to maybe try installing it again in a different way?  If you used pip, maybe try the direct [download](https://github.com/rmjarvis/TreeCorr/releases/tag/v3.2.3) and use the setup.py installation method instead.  And vice versa if you used setup.py, you could try the anaconda version of pip to see if that works any better.

**Comment by jesford** [comment]
Hi Mike - sorry for the delay getting back to this. Previously I had installed with pip, so I tried your suggestion of doing the direct download and setup.py method. To answer your question about the compiler:
```
compiler version information: 
cc (GCC) 4.8.5
```

The install also gives me some several `cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]`. Here is the full output of what I did:
```
$ wget https://github.com/rmjarvis/TreeCorr/archive/v3.2.3.zip
$ unzip v3.2.3.zip
$ cd TreeCorr-3.2.3/
$ ~/anaconda/bin/python2.7 setup.py install
Using setuptools version 20.2.2
Python version =  2.7.10 |Anaconda 2.3.0 (x86_64)| (default, Oct 19 2015, 18:31:17) 
[GCC 4.2.1 (Apple Inc. build 5577)]
running install
running bdist_egg
running egg_info
creating TreeCorr.egg-info
writing requirements to TreeCorr.egg-info/requires.txt
writing TreeCorr.egg-info/PKG-INFO
writing top-level names to TreeCorr.egg-info/top_level.txt
writing dependency_links to TreeCorr.egg-info/dependency_links.txt
writing manifest file 'TreeCorr.egg-info/SOURCES.txt'
reading manifest file 'TreeCorr.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'TreeCorr.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.5-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.macosx-10.5-x86_64-2.7
creating build/lib.macosx-10.5-x86_64-2.7/treecorr
copying treecorr/__init__.py -> build/lib.macosx-10.5-x86_64-2.7/treecorr
copying treecorr/binnedcorr2.py -> build/lib.macosx-10.5-x86_64-2.7/treecorr
copying treecorr/binnedcorr3.py -> build/lib.macosx-10.5-x86_64-2.7/treecorr
copying treecorr/catalog.py -> build/lib.macosx-10.5-x86_64-2.7/treecorr
copying treecorr/celestial.py -> build/lib.macosx-10.5-x86_64-2.7/treecorr
copying treecorr/config.py -> build/lib.macosx-10.5-x86_64-2.7/treecorr
copying treecorr/corr2.py -> build/lib.macosx-10.5-x86_64-2.7/treecorr
copying treecorr/corr3.py -> build/lib.macosx-10.5-x86_64-2.7/treecorr
copying treecorr/field.py -> build/lib.macosx-10.5-x86_64-2.7/treecorr
copying treecorr/ggcorrelation.py -> build/lib.macosx-10.5-x86_64-2.7/treecorr
copying treecorr/gggcorrelation.py -> build/lib.macosx-10.5-x86_64-2.7/treecorr
copying treecorr/kgcorrelation.py -> build/lib.macosx-10.5-x86_64-2.7/treecorr
copying treecorr/kkcorrelation.py -> build/lib.macosx-10.5-x86_64-2.7/treecorr
copying treecorr/kkkcorrelation.py -> build/lib.macosx-10.5-x86_64-2.7/treecorr
copying treecorr/ngcorrelation.py -> build/lib.macosx-10.5-x86_64-2.7/treecorr
copying treecorr/nkcorrelation.py -> build/lib.macosx-10.5-x86_64-2.7/treecorr
copying treecorr/nncorrelation.py -> build/lib.macosx-10.5-x86_64-2.7/treecorr
copying treecorr/nnncorrelation.py -> build/lib.macosx-10.5-x86_64-2.7/treecorr
copying treecorr/util.py -> build/lib.macosx-10.5-x86_64-2.7/treecorr
running build_ext
compiler version information: 
cc (GCC) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Using compiler cc, which is gcc
building 'treecorr._treecorr' extension
creating build/temp.macosx-10.5-x86_64-2.7
creating build/temp.macosx-10.5-x86_64-2.7/src
gcc -fno-strict-aliasing -I/Users/jesford/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Iinclude -I/Users/jesford/anaconda/include/python2.7 -c src/BinnedCorr2.cpp -o build/temp.macosx-10.5-x86_64-2.7/src/BinnedCorr2.o -fopenmp -O3 -ffast-math
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -fno-strict-aliasing -I/Users/jesford/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Iinclude -I/Users/jesford/anaconda/include/python2.7 -c src/BinnedCorr3.cpp -o build/temp.macosx-10.5-x86_64-2.7/src/BinnedCorr3.o -fopenmp -O3 -ffast-math
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -fno-strict-aliasing -I/Users/jesford/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Iinclude -I/Users/jesford/anaconda/include/python2.7 -c src/Cell.cpp -o build/temp.macosx-10.5-x86_64-2.7/src/Cell.o -fopenmp -O3 -ffast-math
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -fno-strict-aliasing -I/Users/jesford/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Iinclude -I/Users/jesford/anaconda/include/python2.7 -c src/Field.cpp -o build/temp.macosx-10.5-x86_64-2.7/src/Field.o -fopenmp -O3 -ffast-math
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
g++ -bundle -undefined dynamic_lookup -L/Users/jesford/anaconda/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.5-x86_64-2.7/src/BinnedCorr2.o build/temp.macosx-10.5-x86_64-2.7/src/BinnedCorr3.o build/temp.macosx-10.5-x86_64-2.7/src/Cell.o build/temp.macosx-10.5-x86_64-2.7/src/Field.o -L/Users/jesford/anaconda/lib -o build/lib.macosx-10.5-x86_64-2.7/treecorr/_treecorr.so -fopenmp
creating build/bdist.macosx-10.5-x86_64
creating build/bdist.macosx-10.5-x86_64/egg
creating build/bdist.macosx-10.5-x86_64/egg/treecorr
copying build/lib.macosx-10.5-x86_64-2.7/treecorr/__init__.py -> build/bdist.macosx-10.5-x86_64/egg/treecorr
copying build/lib.macosx-10.5-x86_64-2.7/treecorr/_treecorr.so -> build/bdist.macosx-10.5-x86_64/egg/treecorr
copying build/lib.macosx-10.5-x86_64-2.7/treecorr/binnedcorr2.py -> build/bdist.macosx-10.5-x86_64/egg/treecorr
copying build/lib.macosx-10.5-x86_64-2.7/treecorr/binnedcorr3.py -> build/bdist.macosx-10.5-x86_64/egg/treecorr
copying build/lib.macosx-10.5-x86_64-2.7/treecorr/catalog.py -> build/bdist.macosx-10.5-x86_64/egg/treecorr
copying build/lib.macosx-10.5-x86_64-2.7/treecorr/celestial.py -> build/bdist.macosx-10.5-x86_64/egg/treecorr
copying build/lib.macosx-10.5-x86_64-2.7/treecorr/config.py -> build/bdist.macosx-10.5-x86_64/egg/treecorr
copying build/lib.macosx-10.5-x86_64-2.7/treecorr/corr2.py -> build/bdist.macosx-10.5-x86_64/egg/treecorr
copying build/lib.macosx-10.5-x86_64-2.7/treecorr/corr3.py -> build/bdist.macosx-10.5-x86_64/egg/treecorr
copying build/lib.macosx-10.5-x86_64-2.7/treecorr/field.py -> build/bdist.macosx-10.5-x86_64/egg/treecorr
copying build/lib.macosx-10.5-x86_64-2.7/treecorr/ggcorrelation.py -> build/bdist.macosx-10.5-x86_64/egg/treecorr
copying build/lib.macosx-10.5-x86_64-2.7/treecorr/gggcorrelation.py -> build/bdist.macosx-10.5-x86_64/egg/treecorr
copying build/lib.macosx-10.5-x86_64-2.7/treecorr/kgcorrelation.py -> build/bdist.macosx-10.5-x86_64/egg/treecorr
copying build/lib.macosx-10.5-x86_64-2.7/treecorr/kkcorrelation.py -> build/bdist.macosx-10.5-x86_64/egg/treecorr
copying build/lib.macosx-10.5-x86_64-2.7/treecorr/kkkcorrelation.py -> build/bdist.macosx-10.5-x86_64/egg/treecorr
copying build/lib.macosx-10.5-x86_64-2.7/treecorr/ngcorrelation.py -> build/bdist.macosx-10.5-x86_64/egg/treecorr
copying build/lib.macosx-10.5-x86_64-2.7/treecorr/nkcorrelation.py -> build/bdist.macosx-10.5-x86_64/egg/treecorr
copying build/lib.macosx-10.5-x86_64-2.7/treecorr/nncorrelation.py -> build/bdist.macosx-10.5-x86_64/egg/treecorr
copying build/lib.macosx-10.5-x86_64-2.7/treecorr/nnncorrelation.py -> build/bdist.macosx-10.5-x86_64/egg/treecorr
copying build/lib.macosx-10.5-x86_64-2.7/treecorr/util.py -> build/bdist.macosx-10.5-x86_64/egg/treecorr
byte-compiling build/bdist.macosx-10.5-x86_64/egg/treecorr/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/treecorr/binnedcorr2.py to binnedcorr2.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/treecorr/binnedcorr3.py to binnedcorr3.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/treecorr/catalog.py to catalog.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/treecorr/celestial.py to celestial.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/treecorr/config.py to config.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/treecorr/corr2.py to corr2.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/treecorr/corr3.py to corr3.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/treecorr/field.py to field.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/treecorr/ggcorrelation.py to ggcorrelation.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/treecorr/gggcorrelation.py to gggcorrelation.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/treecorr/kgcorrelation.py to kgcorrelation.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/treecorr/kkcorrelation.py to kkcorrelation.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/treecorr/kkkcorrelation.py to kkkcorrelation.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/treecorr/ngcorrelation.py to ngcorrelation.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/treecorr/nkcorrelation.py to nkcorrelation.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/treecorr/nncorrelation.py to nncorrelation.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/treecorr/nnncorrelation.py to nnncorrelation.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/treecorr/util.py to util.pyc
creating stub loader for treecorr/_treecorr.so
byte-compiling build/bdist.macosx-10.5-x86_64/egg/treecorr/_treecorr.py to _treecorr.pyc
creating build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
installing scripts to build/bdist.macosx-10.5-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/scripts-2.7
copying and adjusting scripts/corr2 -> build/scripts-2.7
copying and adjusting scripts/corr3 -> build/scripts-2.7
changing mode of build/scripts-2.7/corr2 from 644 to 755
changing mode of build/scripts-2.7/corr3 from 644 to 755
creating build/bdist.macosx-10.5-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/corr2 -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/corr3 -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.macosx-10.5-x86_64/egg/EGG-INFO/scripts/corr2 to 755
changing mode of build/bdist.macosx-10.5-x86_64/egg/EGG-INFO/scripts/corr3 to 755
copying TreeCorr.egg-info/PKG-INFO -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying TreeCorr.egg-info/SOURCES.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying TreeCorr.egg-info/dependency_links.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying TreeCorr.egg-info/requires.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying TreeCorr.egg-info/top_level.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
writing build/bdist.macosx-10.5-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
treecorr.config: module references __file__
treecorr.field: module references __file__
treecorr.ggcorrelation: module references __file__
treecorr.gggcorrelation: module references __file__
treecorr.kgcorrelation: module references __file__
treecorr.kkcorrelation: module references __file__
treecorr.kkkcorrelation: module references __file__
treecorr.ngcorrelation: module references __file__
treecorr.nkcorrelation: module references __file__
treecorr.nncorrelation: module references __file__
treecorr.nnncorrelation: module references __file__
creating dist
creating 'dist/TreeCorr-3.2.3-py2.7-macosx-10.5-x86_64.egg' and adding 'build/bdist.macosx-10.5-x86_64/egg' to it
removing 'build/bdist.macosx-10.5-x86_64/egg' (and everything under it)
Processing TreeCorr-3.2.3-py2.7-macosx-10.5-x86_64.egg
creating /Users/jesford/anaconda/lib/python2.7/site-packages/TreeCorr-3.2.3-py2.7-macosx-10.5-x86_64.egg
Extracting TreeCorr-3.2.3-py2.7-macosx-10.5-x86_64.egg to /Users/jesford/anaconda/lib/python2.7/site-packages
Adding TreeCorr 3.2.3 to easy-install.pth file
Installing corr2 script to /Users/jesford/anaconda/bin
Installing corr3 script to /Users/jesford/anaconda/bin

Installed /Users/jesford/anaconda/lib/python2.7/site-packages/TreeCorr-3.2.3-py2.7-macosx-10.5-x86_64.egg
Processing dependencies for TreeCorr==3.2.3
Searching for pandas==0.17.1
Best match: pandas 0.17.1
Adding pandas 0.17.1 to easy-install.pth file

Using /Users/jesford/anaconda/lib/python2.7/site-packages
Searching for six==1.10.0
Best match: six 1.10.0
Adding six 1.10.0 to easy-install.pth file

Using /Users/jesford/anaconda/lib/python2.7/site-packages
Searching for numpy==1.10.4
Best match: numpy 1.10.4
Adding numpy 1.10.4 to easy-install.pth file

Using /Users/jesford/anaconda/lib/python2.7/site-packages
Searching for pytz==2015.7
Best match: pytz 2015.7
Adding pytz 2015.7 to easy-install.pth file

Using /Users/jesford/anaconda/lib/python2.7/site-packages
Searching for python-dateutil==2.4.2
Best match: python-dateutil 2.4.2
Adding python-dateutil 2.4.2 to easy-install.pth file

Using /Users/jesford/anaconda/lib/python2.7/site-packages
Finished processing dependencies for TreeCorr==3.2.3
```

Then, in ipython, importing gives a different error than before:
```
In [1]: import treecorr
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-1-88d203157b69> in <module>()
----> 1 import treecorr

/Users/jesford/astrophysics/TreeCorr-3.2.3/treecorr/__init__.py in <module>()
     17 from . import util
     18 from .celestial import CelestialCoord, angle_units, arcsec, arcmin, degrees, hours, radians
---> 19 from .config import read_config, set_omp_threads
     20 from .catalog import Catalog, read_catalogs, calculateVarG, calculateVarK
     21 from .binnedcorr2 import BinnedCorr2

/Users/jesford/astrophysics/TreeCorr-3.2.3/treecorr/config.py in <module>()
    346 import numpy
    347 import ctypes
--> 348 _treecorr = numpy.ctypeslib.load_library('_treecorr',os.path.dirname(__file__))
    349 _treecorr.SetOMPThreads.restype = ctypes.c_int
    350 _treecorr.SetOMPThreads.argtypes = [ ctypes.c_int ]

/Users/jesford/anaconda/lib/python2.7/site-packages/numpy/ctypeslib.pyc in load_library(libname, loader_path)
    126                     raise
    127         ## if no successful return in the libname_ext loop:
--> 128         raise OSError("no file with expected extension")
    129 
    130     ctypes_load_library = deprecate(load_library, 'ctypes_load_library',

OSError: no file with expected extension
```

Like I said, I had no trouble installing and using treecorr in my Python 3 environment, but it would be great to figure out why this isn't working for me in Python 2. Thanks so much for your help with this!

**Comment by rmjarvis** [comment]
First, it looks like you are running python from within the TreeCorr directory.  Don't do this.  It's finding the local copy rather than the installed copy.

Second, is this El Capitan?  If so, there may be issues related to a new "security" feature that Apple instituted there.  We've been struggling with that for GalSim (cf. [this issue](https://github.com/GalSim-developers/GalSim/pull/725)).  I don't have an El Capitan system to try this on, but it's possible there is something that needs to be changed here to make it work for that.

**Comment by jesford** [comment]
Ah, ok. Importing treecorr from another directory then gives me the same error as it did when I pip installed the package. I'm on Yosemite 10.10.5.

**Comment by rmjarvis** [comment]
OK.  So neither of those then.  Let me try updating my Anaconda distro then to see if I can reproduce what you are seeing.  I still have 2.0.0.

**Comment by rmjarvis** [comment]
I upgraded to 2.3.0 and didn't have a problem.  However, I notice that your cc is fsf-gcc 4.8.5 rather than clang, which is the default (I thought!) on Yosemite.  Did you do something on your system to overwrite the default compiler?

**Comment by jesford** [comment]
Hmm, I think I actually may have done that a little while back... I'll look into switching back to the default compiler. Thanks for your help!

**Pull request merged**
